# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
  branches:
    include:
      - refs/heads/*
      - refs/tags/*

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-latest'
    mac:
      imageName: 'macos-10.14'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
# Linux
- bash: |
    curl -O https://www.libsdl.org/release/SDL2-2.0.9.tar.gz
    tar -xzf SDL2-2.0.9.tar.gz
    pushd SDL2-2.0.9/ 
    mkdir $HOME/SDL
    ./configure --prefix=$HOME/SDL
    make
    make install    
    export PATH=$HOME/SDL/bin:$PATH
    popd
    cd AGSController
    make
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'make'

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Linux' )
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/AGSController'
    contents: 'libagscontroller.so'
    targetFolder: $(Build.ArtifactStagingDirectory)

# macOS
- bash: |
    pushd ~
    curl -O https://www.libsdl.org/release/SDL2-2.0.9.dmg
    hdiutil attach SDL2-2.0.9.dmg
    sudo cp -a /Volumes/SDL2/SDL2.framework /Library/Frameworks/
    pushd /Library/Frameworks/SDL2.framework/
    codesign -f -s - SDL2
    popd
    popd
    cd AGSController
    make
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: 'make'

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Darwin' )
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/AGSController'
    contents: 'libagscontroller.dylib'
    targetFolder: $(Build.ArtifactStagingDirectory)

# Windows

- bash: |
    curl -O https://www.libsdl.org/release/SDL2-devel-2.0.9-VC.zip
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  displayName: 'downloadSDL'

- powershell: |
    mkdir C:\Dev
    7z x -y "SDL2-devel-2.0.9-VC.zip" -o"C:\Dev"
    Rename-Item C:\Dev\SDL2-2.0.9 C:\Dev\SDL2
  condition: eq( variables['Agent.OS'], 'Windows_NT' )   
  displayName: 'extractSDL'

- task: VSBuild@1
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  inputs:
    solution: 'AGSController\vs2017\AGSController.sln' 
    platform: win32
    configuration: Release

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Windows_NT' )   
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/AGSController/vs2017/Release'
    contents: 'AGSController.dll'
    targetFolder: $(Build.ArtifactStagingDirectory)

- bash: |
    echo "##vso[task.setvariable variable=tagname]$(git describe --tags $(git rev-list --tags --max-count=1))"
# Upload to Github Release
- task: GithubRelease@0 
  displayName: 'Create GitHub Release'  
  inputs:
    tagSource: 'auto'
    tag: $(tagname)
    assetUploadMode: 'replace' 
    action: 'edit' 
    gitHubConnection: agscontroller
    repositoryName: ericoporto/AGS-Controller           
    assets: |
         $(Build.ArtifactStagingDirectory)/*.dll
         $(Build.ArtifactStagingDirectory)/*.so
         $(Build.ArtifactStagingDirectory)/*.dylib
